baseurl = "http://petschau.github.io/WinFellow"
languageCode = "en-us"
title = "WinFellow - Amiga Emulator for Windows"
theme = "twentyfourteen-tags"

[taxonomies]
tag = "tags"

[blackfriday]
    hrefTargetBlank = true

[[menu.main]]
    name = "RSS"
    weight = 0
    url = "/post/index.xml"
    
[[menu.external]]
    name = "Downloads"
    weight = 10
    url = "https://github.com/petschau/WinFellow/releases"

[[menu.external]]
    name = "GitHub"
    weight = 30
    identifier = "GitHub"
    url = "http://github.com/petschau/WinFellow"

[[menu.external]]
    name = "sf.net Archive"
    weight = 35
    url = "http://fellow.sf.net/new_version"
